### PR TITLE
Adapted `pander.mtable` to new version of "memisc" package.

### PR DESCRIPTION
**Pull request by melff**
This time it should past the tests ...

### CODE REVIEW

**Comment by daroczig** [comment]
Thank you very much for this patch! @RomanTsegelskyi, as you wrote the original `mtable` method, can you please look into this?

**Comment by RomanTsegelskyi** [comment]
@melff, thanks a lot for the PR, it looks great. Just one small not, any reason why you decided to remove

```r
if (is.null(caption) & !is.null(storage$caption)) {
      caption <- get.caption()
}
```

**Comment by melff** [comment]
@RomanTsegelskyi There is no conscious decision of removing it. I rewrote `pander.mtable` new from scratch and this slipped through. Shall I create a new pull request?

**Comment by RomanTsegelskyi** [comment]
@melff, no need to create new PR, update here is fine

**Comment by melff** [comment]
Yep, just noticed it when I pushed a new commit :)

**Comment by daroczig** [comment]
Thank you very much, both! This looks awesome, so happily merging the PR.

@melff one question though: is there any easy way to decide if an `mtable` object was generate with `memisc` 0.99+ or lower? This way we could check the version of the object, and run the old method for the deprecated versions -- so both version could be supported by `pander`. That's what we do with `ggplot2` for the unified graph features.

**Comment by melff** [comment]
Before 0.99, the "coefficients" component of an "mtable" object was an array or rather a "table" object, since 0.99 it is a list.

**Pull request merged**
