### PR TITLE
Removing and deprecating return functions

### PR DESCRIPTION
**Pull request by RomanTsegelskyi**
Intention to deprecate and eventually remove `_return` as discussed in #168. This PL will serve as aggregation of comments to implement things discussed.

### CODE REVIEW

**Comment by RomanTsegelskyi** [comment]
@daroczig, I working on removing `_return` functions and there is one complication which I am not sure how to resolve best. Removing `pander_return` does not seems to cause any problems and seems to work and look rather organic. But that is not the case with `pandoc.*.return`. 

For example, `pandoc.strong.return`. Original code is, 

```r
pandoc.strong.return <- function(x)
    pandoc.add.formatting(x, '**')

#' @export
pandoc.strong <- function(...)
    cat(pandoc.strong.return(...))
```

And my ideas was to change it to 

```r
pandoc.strong.return <- function(...) {
    .Deprecated('pandoc.strong')
    capture.output(pandoc.strong(...))
}

#' @export
pandoc.strong <- function(x {
    cat(pandoc.add.formatting(x, '**'))
}
```

But since we need a capture output of `pandoc.strong` for example in [pandoc.table.return](https://github.com/Rapporter/pander/blob/master/R/pandoc.R#L951) it results in a cat -> capture.output sequence and also introduces some a bag. It results in all rownames being glued in each row.

```r
> pander(data.frame(mtcars[1:2,1:3]))

----------------------------------------------
          &nbsp;             mpg   cyl   disp 
--------------------------- ----- ----- ------
 **Mazda RX4** **Mazda RX4   21     6    160  
           Wag**                              

 **Mazda RX4** **Mazda RX4   21     6    160  
           Wag**                              
----------------------------------------------
```

This happend because of how `cat` works. Vector is printed in one line and the when output is captured it just becomes a vector of one string.

```r
> x <- c("a","b","c")
> capture.output(cat(x))
[1] "a b c"
```

This can be worked around by rewriting functions like `pandoc.add.formatting` to output rather than return a character vector, but it makes code a bit more messy. So I was thinking that for `pandoc.*` functions it reasonable to have a param to return a character vector.  What do you think?

**Comment by daroczig** [comment]
Hm, this is indeed tricky. I should have spent a lot more time on design when coming up with this package structure :( Probably it might have been cleaner to have `pandoc...` fns always return character vector and `pander` to print to stdout.

Anyway, about next steps: I'll have to think about it or rather we should brain-strorm on it together after the R/Finance 2015 conference ended. Until then: what's the advantage of having an extra argument compared to the current approach?

**Comment by RomanTsegelskyi** [comment]
I think it's a very reasonable idea to have `pandoc...` fns always return a character vector. IMHO most users of the package are calling `pander` function and `pandoc...` ones are used mostly internally and in the whole package seems like `pandoc.table` and `pandoc.list` is used to print the output, while all other `pandoc...` functions are used through `_return` version.

That said, I feel that just having an argument/option to print or completely removing `pandoc...` fns that produce output will simplify the code base from the functions that seem not be used anyway. 

I will also try to think about it more in the meantime and maybe do more exploration, so we can share the ideas when the R/Finance is over

**Comment by daroczig** [comment]
After all, I am not 100% sure about this change.

My concern now is, that the `pandoc.foo.return` functions does not brake any CRAN checks, recommendation or naming conventions, so there is no urgent need to change things, like with `pander.return`. On the other hand, `pandoc.table` is more frequently used than the main `pander` method -- not sure why this is widely used all over StackOverflow and in a few blog posts :(

It would be great to see the usage pattern of the users, but based on the related SO questions, I think `pandoc.table` and `pander` are used in most cases, and both writing to `stdout`. Based on that, I'd say let's not bother with the `.return` functions -- let's just stick to the original plan by renaming `pander.return` to `pander_return`, which hopefully will simply die out soon.

@RomanTsegelskyi, how do you see this after sleeping a few days on this problem?

**Comment by RomanTsegelskyi** [comment]
@daroczig, after I look a bit more into SO, I think it's reasonable to leave it as is for now and stick to original plan of just renaming `pander.return` to `pander_return`. Still I think that we should consider removing `pandoc.*` (like pandoc.p, etc) later since they seem to be barely used even inside the package. But that indeed doesn't seem even medium priority, so I think it is reasonable to do what we planned now and come back with more research closer to the end of summer when other goals are fullfilled.

**Comment by daroczig** [comment]
Cool. Then can you please push a new commit to this branch so that we can merge? You have fixed a bunch of important things here, and I think we can leave the `capture.output` calls there as well (no need to revert to `.return`), but `pander_return` shouldn't be deprecated. Anything else?

**Comment by RomanTsegelskyi** [comment]
@daroczig that seems to be it. In the end I decided to leave all `pandoc.*` calls unchanged to avoid any potential issues, so I submitted #178 where just `pander.return` usages are cleaned out.

**Pull request closed without merging**
