### PR TITLE
pander: pander.tabular

### PR DESCRIPTION
**Pull request by Dongcan-Jiang**
The patch implements a method for table::tabular as pander.tabular which
can work with any number of variables with even complex table layouts.[1]

One test case is added to test-S3.R. In this case, a tabular object is created
by tables::as.tabular instead of tabular, so that the test file has no need to 
load the whole 'tables' library, which I think would be better.

The document of pander.tabular is added by roxygen2 (4.1.0) referring to
Alexis L.[2]

You can run the test by:

    > library(tables)
    > library(pander)
    > x <- tabular(as.factor(am) ~ (mpg+hp+qsec) * (mean+median), data = mtcars)
    > pander(x, digits=2, emphasize.rownames=FALSE)

[1] https://github.com/rstats-gsoc/gsoc2015/wiki/pander
[2] https://github.com/YoruNoHikage/pander/blob/master/man/pander.tabular.Rd

Helped-by: Gergely Darócz <daroczig@rapporter.net>
Signed-off-by: Dongcan Jiang <dongcan.jiang@gmail.com>

### CODE REVIEW

**Comment by daroczig** [comment]
Thank you! To make this pull request more complete, can you please also add a few test cases, so that coveralls would not deny it? It would be also very useful to present the added value of this application.

**Comment by Dongcan-Jiang** [comment]
@daroczig Thanks for your comments. I've added the test and document then repushed it. But the Travis CI failed. I am very confused about the reason in log "The command "sudo apt-get install r-base-dev pandoc qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra libxml2-dev" failed and exited with 100 during ." Could you give me some suggestions? Thanks.

**Comment by RomanTsegelskyi** [comment]
Sometimes `Travis` fails for reasons not dependent on code and in this case it seems so. Try just restarting Travis job manually

**Comment by daroczig** [comment]
Thank you, guys -- I've restarted the Travis job. And yeah, this happens sometimes. Will update Travis to use Rocker instead of the apt-get heavy commands, which should be a lot faster.

**Comment by Dongcan-Jiang** [comment]
@daroczig @RomanTsegelskyi Thank you. I've added the test and passed the coveralls.

**Comment by daroczig** [comment]
Thank you very much, this is a very valuable pull request. Please do not forget to register later on Google Melange as part of the official GSoC application with a complete program. Also, if you end up with any further improvements to this PR, please push those as well later. I think @RomanTsegelskyi's version is more mature ATM.

**Comment by daroczig** [comment]
Thank you very much for this submission, but #161 was accepted for GSoC 2015 after all.

**Pull request closed without merging**
