### PR TITLE
Adding the numeric p-value to the output of class htest, 

### PR DESCRIPTION
**Pull request by s1lvester**
whilst keeping the significance stars.
Maybe one could change the number of digits in the round() function to global pander variable name but I didn't find that on the fly.

### CODE REVIEW

**Comment by daroczig** [comment]
Wow, this bug was introduced a [while ago](https://github.com/s1lvester/pander/commit/be421bf410f4c44e2c95bdfc5a24af5042805117) -- thanks a lot for the fix!

Can you replace that hardcoded `5` with `panderOptions('round')` for the consistency of the package and even wrapping that in `format` like we do in the `p` function and inside of the markdown tables? Also, why do we need the `c` function? I think it's safe to remove that around the `paste` call. Last Q: shouldn't we add the significance stars after the actual P value? E.g.:

```r
res$'P value' <- paste(
    format(round(x$p.value, panderOptions('round')),
           trim         = TRUE,
           digits       = panderOptions("digits"),
           decimal.mark = panderOptions("decimal.mark")),
    add.significance.stars(x$p.value))
```

**Comment by s1lvester** [comment]
Your fix is even better. :-)

**Comment by s1lvester** [comment]
so the latest patch (4ead3f5) works fine for me. Although my results aren't that great, but that' another story...

3_tests

**Comment by daroczig** [comment]
Thanks for this. And good luck with the results :)
One question about that: the stars seem to be in front of the P value. Is it intended? The currently merged code should render that after the numeric value.

**Comment by s1lvester** [comment]
No it wasn't inteded. I forgot to delete the caches and re-knit the html output... It's all good now :)

**Pull request merged**
