### PR TITLE
add logging functionality to evals/Pandoc.brew

### PR DESCRIPTION
**Pull request by daroczig**

### CODE REVIEW

**Comment by daroczig** [comment]
@RomanTsegelskyi, have you seen this? What do you think? Any further ideas on what could be logged? I'd love to merge this as well in the near future (~before next CRAN release) with some extra test coverage.

**Comment by RomanTsegelskyi** [comment]
@daroczig I will definitely look into in the nearest future when I will write more tests for `evals`

**Comment by daroczig** [comment]
Thanks a lot! Please note that `evals` is another mammoth, just like `pandoc.table` -- with some really tricky parts (like caching or injecting updated versions of the base `graphics` functions for unified plots). Let me know if you need any help here.

**Comment by RomanTsegelskyi** [comment]
@daroczig I looked through the code, add a bit more logging. I feel that this can be merged and then I will get into more refactoring of `evals`. What do you think?

**Comment by daroczig** [comment]
Cool! It's seems to be safe to merge, there was an issue previously with https://github.com/zatonovo/futile.logger/pull/27 -- it's live on CRAN now.

Now that you have looked through the source code of `evals`, any plans on refactoring? The most of the code base was written ~2-3 years ago, so I suspect some funny things lurking there, although I remember I was pretty proud of the features at that time :)

Let me know what you think.

**Comment by RomanTsegelskyi** [comment]
I definitely want to refactor some parts, I just wanted to merge the pull request first, not to have conflicts. In general I plan to spend next days (probably until end of next week) to do refactoring where I can, try to get everything under consistent style, maybe write more tests after I add braces to all the if statements and fix 2 remaining issues. And after that I think we will have a package ready for a new release and I will move to working on new S3 methods/vignettes and more feature.

**Comment by daroczig** [comment]
Great, let me know if you need any help.

**Pull request merged**
