### PR TITLE
Evals refactoring + more testing

### PR DESCRIPTION
**Pull request by RomanTsegelskyi**
More refactoring of `evals`

### CODE REVIEW

**Comment by daroczig** [comment]
Thanks a lot, it looks great. Did you verify we do not need that double `lapply` call? Not sure why we had that previously.

**Comment by RomanTsegelskyi** [comment]
I spend a bit more time trying different calls and I am sure that second `lapply` was not needed. After all there is a recursion anyway for `getCallParts`

**Comment by RomanTsegelskyi** [comment]
I am sorry, you are right. I didn't account for the case when parameters to hooks are not named

**Comment by daroczig** [comment]
Looks good, IMO ready to merge. And mentioning here as well: I'd love to have a vignette on the features of `evals`. It has some nifty features :) Anyway, thanks for this.

**Pull request merged**
