### PR TITLE
Unified code style and lintr

### PR DESCRIPTION
**Pull request by RomanTsegelskyi**
@daroczig, what would you think about unifying the code style and getting adding `lintr` to CI? If yes, I will expand this PR for the whole code base.

I looked at `default_linters` and all of them are applicable except for `single_quotes_linter` (we agreed to use single quotes) and `line_length_linter` (probably we should default to `120`). What do you think?

### CODE REVIEW

**Comment by daroczig** [comment]
Yeah, that's a great idea -- I wanted to do that a long time ago, although I suspect some other things to override (like the `pandoc.foobar` function family). Do you also plan to add `lintr` to Travis, just like `covr`?

**Comment by RomanTsegelskyi** [comment]
Actually I thinking about maybe moving CI to [Wercker](https://app.wercker.com)(it seems to be a bit more faster and has `Rocker` containers support) and codecov.io (somehow coveralls stopped getting correct coverage).

I have another question about other overrides with default linter. There are 2 linters between which I can't choose:
* `camel_case_linter`: check that objects are not in `camelCase`.
* `snake_case_linter`: check that objects are not in `snake_case`.

There seem to be a mixture between those 2 styles in the code. I would prefer `snake_case` style, but some of the function parameters are in `camelCase`, so changing them is probably not that good of idea. Which style do you think we should stick with?

**Comment by daroczig** [comment]
Sorry for the long delay with my reply. Most function arguments are using the dot notation, nope?

**Comment by daroczig** [comment]
Repo created: https://codecov.io/github/Rapporter/pander

**Comment by RomanTsegelskyi** [comment]
Yeah, mostly dot notation, just `showInvisible` argument for `evals`. In general I feel that we should just leave that check out, but not 100% sure

**Comment by daroczig** [comment]
Yeah, that makes sense: let's leave this check out (for now). And maybe later we will be able to resolve this as well.

**Comment by RomanTsegelskyi** [comment]
@daroczig, I think I am done with lintering and unifying code style. Okay to merge?

**Comment by RomanTsegelskyi** [comment]
My rationale behind looking for `futile.logger` in `installed.packages`, was that `required` or `library` give a NOTE with R CMD check:
```
* checking dependencies in R code ... NOTE
'library' or 'require' call to ‘futile.logger’ in package code.
  Please use :: or requireNamespace() instead.
```
I just figure that I should use `requireNamespace()` instead like I did with `koRpus`.

About `lintr` and single quotes. `lintr` only supports a check for usage of double quotes. I disabled that check and was trying to write one that checks single quotes, but was not yet successful.

**Comment by daroczig** [comment]
Yeah, `requireNamespace` seems like the best approach.

**Pull request merged**
