### PR TITLE
Move functions related to `pander` in `ggthemes` back to `pander`

### PR DESCRIPTION
**Pull request by jrnold**
You had contributed these functions to `ggthemes` (thanks!). But I think that it makes more sense for them to be in `pander` due to their coupling with `panderOptions`. R CMD check is much less forgiving of using `require` now. With updates to the development version of R,  I wrote a workaround so that these functions would continue to work in `ggthemes`, but, I don't think it's elegant. The code is much clearer, and likely easier to maintain, if it resides in `pander`.

### CODE REVIEW

**Comment by daroczig** [comment]
Thank you, @jrnold.

To be honest, I am not sure if these functions belong here if `ggthemes` is intended to be a collection of different `gplot2` themes -- so I would try to discuss the options first.

What's wrong with using 'pander::panderOptions` instead of the `getFromNamespace` workaround as described at http://cran.r-project.org/doc/manuals/r-patched/R-exts.html#Suggested-packages?

**Comment by jrnold** [comment]
`ggthemes` is intended to be a collection of `ggplot2` themes, so I'm glad to host the theme. But it seems to me that `theme_pander` is as much, if not more-so, an interface between `pander` and `ggplot2` than a stand-alone theme. The functions seem primarily ways to generate themes and palettes that recognize the default options from pander, which makes more coupled with `pander` than with anything else. I'm fine keeping it in `ggthemes` if you help maintain it. I got Ripley'd in the last update of R for it, and I don't follow the development of pander.  If `panderOptions` change, I won't catch it until it throws a bug somewhere.

**Comment by daroczig** [comment]
Thanks a lot, @jrnold!

I'm happy to maintain any `pander`-related part of your package and would notify you prior to do any serious updates in `panderOptions` -- although that I do not really plan to touch that part of `pander` in the near future.

I'm terribly sorry to hear about being Ripley'd -- I've also experienced that extremely bad feeling in the past :(  I'm running some tests on your current codebase so that you would not get in such bad situation again -- sorry for that.

**Comment by jrnold** [comment]
Yeah, let's just keep in `ggthemes`. The code in `ggthemes` is fine (at least as much as any :) ); it was just changes to `R CMD check` in the latest version of R to require that `require` not be in packages caused some issues with the `pander` related code in `ggthemes`.

**Comment by daroczig** [comment]
I've just installed the most recent dev version of `R` (r68058) to run the checks, and it seems to be OK for now :)

**Pull request closed without merging**
