### PR TITLE
make calls verbatim, add support for symbols

### PR DESCRIPTION
**Pull request by daroczig**
@RomanTsegelskyi not sure why we returned calls as formulas previously, do you remember? I've just had a real-life need for `pander.call` and using inline verbatim seems much more useful. Maybe we can make this behavior optional, but first I wanted to ask you opinion on this.

### CODE REVIEW

**Comment by RomanTsegelskyi** [comment]
@daroczig, yes, there was an idea to unify `formula` and `call` (https://github.com/Rapporter/pander/pull/91) last summer. I agree that inline verbatim is indeed more useful. Do you think I should a change to `pandoc.formula` to support `verbatim` option?

**Comment by daroczig** [comment]
I think a simple `deparse`, like what we do now, should be OK. Any ideas why this would not work?

After all, I think statistical formulas and R calls are very different creatures, so there's no need to handle those with the same helper function. I was just not sure if there might be any side effect by changing the behavior of the old `pander.call`, but your answer suggests it's fine. OK to merge?

**Comment by RomanTsegelskyi** [comment]
You mean `deparse` for `formula` too? That would work, just current `pandoc.formula` supports a bit more options(like caption, additional text, additional line breaks). Yes, it seems okay to merge though.

**Comment by daroczig** [comment]
No, I do not want to mess with up `pander.formula` -- that's fine, I meant only `pander.call.` Merging :)

**Pull request merged**
