### PR TITLE
fix link to cran

### PR DESCRIPTION
**Pull request by njahn82**

### CODE REVIEW

**Comment by daroczig** [comment]
Thanks for this! Can I please ask you to update the PR to edit the `inst/README.brew` file instead of the actual `README.md`? This file is actually auto-generated from the `brew` file.

**Comment by njahn82** [comment]
Alright, I was not aware of the brew file.

**Comment by njahn82** [comment]
Alright, I was not aware of `inst/README.brew` . It should be fixed now.

**Comment by daroczig** [comment]
Much appreciated!

**Pull request merged**
